name: CI/CD

on:
  push:
    branches: [ '**' ] # this triggers only on branch commits, which prevents triggering off of tag-only commits
    paths-ignore:
      - .github/workflows/move-tags.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/dev@v0
      - name: Parse version
        id: parse
        uses: ./.github/actions/version
        with:
          semver: ${{ env.VERSION }}
